/**
 * Client for the tier-2 mobility backend job protocol (OCOKA 5,
 * docs/ROUTE_INTELLIGENCE.md §47.3) — `POST /mobility/jobs` +
 * `GET /mobility/jobs/{jobId}`, served by the separate `api-mobility`
 * Function App (see that package's own README.md for why it's separate
 * from `/api` today).
 *
 * `MobilityJobRequest`/status types here are the webapp half of the THIRD
 * webapp/api must-match pair (`api-mobility/src/types/mobilityJob.ts` is the
 * other half — check both when touching either).
 *
 * `VITE_MOBILITY_API_BASE_URL` doubles as this feature's flag: unset (the
 * default — nothing is deployed pre-cutover) means `isMobilityBackendConfigured()`
 * is false and callers should not show a tier-2 trigger at all, rather than
 * offering a button that can only ever 404.
 */

export interface MobilityJobBounds {
  minLat: number;
  minLng: number;
  maxLat: number;
  maxLng: number;
}

export type MobilityJobFidelity = 'quick' | 'standard' | 'fine';

export interface MobilityJobRequest {
  originBounds: MobilityJobBounds;
  objectiveBounds: MobilityJobBounds;
  moverProfileId: string;
  nightMode: boolean;
  fidelity: MobilityJobFidelity;
}

export type MobilityJobArtefactKind = 'grid-summary' | 'route' | 'corridors' | 'obstacles' | 'key-terrain';

export interface MobilityJobArtefact {
  seq: number;
  kind: MobilityJobArtefactKind;
  blobPath: string;
  /** Freshly-minted, read-only, single-blob SAS URL — regenerated by the
   *  server on every status poll (never cached client-side across polls). */
  url: string;
}

export type MobilityJobPhase = 'running' | 'complete' | 'failed';

export interface MobilityJobStatusResponse {
  jobId: string;
  phase: MobilityJobPhase;
  provisional: boolean;
  artefacts: MobilityJobArtefact[];
  incompleteStages?: string[];
  error?: string;
  startedAt: string;
  updatedAt: string;
}

const baseUrl = (import.meta as any).env?.VITE_MOBILITY_API_BASE_URL as string | undefined;

/** Whether a tier-2 backend endpoint is configured for this deployment.
 *  False in every deployment until the owner sets `VITE_MOBILITY_API_BASE_URL`
 *  (pre-cutover: the standalone Function App's own URL; post-cutover: `/api`). */
export function isMobilityBackendConfigured(): boolean {
  return !!baseUrl;
}

export class MobilityJobSubmitError extends Error {
  constructor(message: string, readonly status?: number) {
    super(message);
  }
}

/** Submits a tier-2 job. Throws `MobilityJobSubmitError` on any non-2xx or
 *  network failure — unlike the assistant client's graceful-null pattern,
 *  a failed SUBMIT has no useful degraded state to fall back to, so the
 *  caller must surface it. */
export async function submitMobilityJob(request: MobilityJobRequest): Promise<{ jobId: string; statusUrl: string }> {
  if (!baseUrl) throw new MobilityJobSubmitError('Tier-2 backend is not configured for this deployment');
  const resp = await fetch(`${baseUrl.replace(/\/$/, '')}/mobility/jobs`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(request),
  });
  if (!resp.ok) {
    let detail = '';
    try { detail = (await resp.json())?.error ?? ''; } catch { /* ignore */ }
    throw new MobilityJobSubmitError(detail || `Job submit failed (HTTP ${resp.status})`, resp.status);
  }
  return resp.json();
}

/** Fetches the current status for one job — pointers + fresh SAS URLs.
 *  Returns `null` on network failure or a non-2xx (mirrors this project's
 *  other API clients' graceful-degrade convention) — the caller's own
 *  polling loop decides how many consecutive nulls to tolerate before
 *  giving up. */
export async function fetchMobilityJobStatus(statusUrl: string): Promise<MobilityJobStatusResponse | null> {
  if (!baseUrl) return null;
  try {
    const resp = await fetch(`${baseUrl.replace(/\/$/, '')}${statusUrl}`);
    if (!resp.ok) return null;
    return await resp.json();
  } catch {
    return null;
  }
}
